name: Build Pokémon Abdel Edition

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer les outils
        run: |
          sudo apt-get install -y unzip gcc-arm-none-eabi binutils-arm-none-eabi build-essential libpng-dev
      - name: Décompresser le projet
        run: |
          mkdir project
          unzip -q Pokemon_Emeraude_Abdel_Edition_GITHUB_READY_FIXED.zip -d project
      - name: Corriger les noms de capacités
        working-directory: project/pokeemerald-fr-master
        run: |
            sed -i 's/Garde Mystique/Garde Mystik/g' src/data/text/abilities.h
            sed -i 's/Ecaille Spéciale/Ecaille Spec/g' src/data/text/abilities.h
      - name: Trouver le projet
        run: |
          find project -name Makefile -print

      - name: Installer agbcc
        run: |
          git clone --depth 1 https://github.com/pret/agbcc.git
          cd agbcc
          ./build.sh
          ./install.sh ../project/pokeemerald-fr-master
      - name: Donner les droits aux outils
        working-directory: project/pokeemerald-fr-master
        run: |
          chmod +x tools/gbafix/gbafix
          chmod +x tools/gbagfx/gbagfx
      - name: Compiler scaninc    
        working-directory: project/pokeemerald-fr-master
        run: |
          make -C tools/scaninc 
      - name: Compiler le jeu
        working-directory: project/pokeemerald-fr-master
        run: |
          pwd
          echo "=== CONTENU DU PROJET ==="
          ls -la
          echo "=== COMPILATION ==="
          make -j1 all

      - name: Vérifier la ROM
        working-directory: project/pokeemerald-fr-master
        run: |
          echo "=== ROMS TROUVEES ==="
          ls -lh *.gba
          test -s pokeemerald.gba
          echo "=== SHA1 ==="
          sha1sum pokeemerald.gba

      - name: Récupérer la ROM
        uses: actions/upload-artifact@v4
        with:
          name: Pokemon-Emeraude-Abdel-Edition
          path: project/pokeemerald-fr-master/pokeemerald.gba
          if-no-files-found: error
          retention-days: 7
